### ISSUE TITLE
CuPy backend

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api-strict#5]
We may want to move cupy.array_api to this library as a cupy backend. That would provide support for non-trivial device support, which is currently the one thing that can't really be checked that much through the usage of this library alone.

**Comment by leofang** [comment]
Q: What's the plan for `numpy.array_api`? That it'd be moved to this repo starting NumPy 2.0?

cc: @kmaehashi for vis

**Comment by asmeurer** [comment]
Yes, the plan is to remove it for 2.0.

**Comment by lucascolley** [comment]
We've just switched from `numpy.array_api` in SciPy - https://github.com/scipy/scipy/pull/20087

**Comment by asmeurer** [comment]
This is looking like a won't fix. We can emulate all the major standard behavior of CuPy, including now device support. Supporting multiple backends would be a major testing and maintenance headache that wouldn't be worth it.
